#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "ast.h"
#include "parser.tab.h"
#include "symbol.h"
#include "semantic.h"
#include "codegen.h"
#include "vm.h"

extern FILE *yyin;
extern int yyparse(void);
extern ASTNode *ast_root;

/* ============================================================================
 *  Command Line Options
 * ============================================================================ */

typedef struct {
    const char *input_file;
    const char *output_file;   /* -o: Output bytecode file */
    bool show_ast;         /* -a: Show AST */
    bool show_symbols;     /* -s: Show symbol table */
    bool show_bytecode;    /* -c: Show generated bytecode */
    bool run_program;      /* -r: Run the program (default) */
    bool debug_vm;         /* -d: Debug VM execution */
    bool help;             /* -h: Show help */
} Options;

static void print_usage(const char *prog_name) {
    printf("Kullanim: %s [secenekler] <dosya.tc>\n\n", prog_name);
    printf("TurkC Derleyici ve Sanal Makine - Project 3\n\n");
    printf("Secenekler:\n");
    printf("  -a    AST'yi goster\n");
    printf("  -s    Sembol tablosunu goster\n");
    printf("  -c    Uretilen bytecode'u goster\n");
    printf("  -o FILE Bytecode'u dosyaya kaydet\n");
    printf("  -r    Programi calistir (varsayilan)\n");
    printf("  -d    VM debug modu (adim adim calistirma)\n");
    printf("  -h    Bu yardim mesajini goster\n");
    printf("\nOrnekler:\n");
    printf("  %s program.tc           # Derle ve calistir\n", prog_name);
    printf("  %s -c program.tc        # Bytecode'u goster\n", prog_name);
    printf("  %s -a -s program.tc     # AST ve sembol tablosunu goster\n", prog_name);
}

static Options parse_options(int argc, char **argv) {
    Options opts = {0};
    opts.run_program = true;  /* Default */
    
    for (int i = 1; i < argc; i++) {
        if (argv[i][0] == '-') {
            if (argv[i][1] == 'o' && argv[i][2] == '\0') {
                /* -o requires next argument */
                if (i + 1 < argc) {
                    opts.output_file = argv[++i];
                } else {
                    fprintf(stderr, "-o secenegi dosya adi gerektirir\n");
                    opts.help = true;
                }
            } else {
                for (int j = 1; argv[i][j]; j++) {
                    switch (argv[i][j]) {
                        case 'a': opts.show_ast = true; break;
                        case 's': opts.show_symbols = true; break;
                        case 'c': opts.show_bytecode = true; break;
                        case 'r': opts.run_program = true; break;
                        case 'd': opts.debug_vm = true; break;
                        case 'h': opts.help = true; break;
                        default:
                            fprintf(stderr, "Bilinmeyen secenek: -%c\n", argv[i][j]);
                            opts.help = true;
                            break;
                    }
                }
            }
        } else {
            opts.input_file = argv[i];
        }
    }
    
    return opts;
}

/* ============================================================================
 *  Main Entry Point
 * ============================================================================ */

int main(int argc, char **argv) {
    Options opts = parse_options(argc, argv);
    
    if (opts.help || !opts.input_file) {
        print_usage(argv[0]);
        return opts.help ? EXIT_SUCCESS : EXIT_FAILURE;
    }
    
    /* ========== Phase 1: Parsing (from Project 2) ========== */
    printf("=== TurkC Derleyici v3.0 ===\n");
    printf("Dosya: %s\n\n", opts.input_file);
    
    yyin = fopen(opts.input_file, "r");
    if (!yyin) {
        perror(opts.input_file);
        return EXIT_FAILURE;
    }
    
    printf("[1/4] Parsing (sozdizimi analizi)...\n");
    int parse_result = yyparse();
    fclose(yyin);
    
    if (parse_result != 0) {
        fprintf(stderr, "\nParsing basarisiz oldu.\n");
        if (ast_root) ast_free(ast_root);
        return EXIT_FAILURE;
    }
    
    if (!ast_root) {
        fprintf(stderr, "AST olusturulamadi.\n");
        return EXIT_FAILURE;
    }
    
    printf("      Parsing basarili.\n");
    
    /* Show AST if requested */
    if (opts.show_ast) {
        printf("\n=== Soyut Sozdizim Agaci (AST) ===\n");
        ast_print(ast_root, 0);
    }
    
    /* ========== Phase 2: Semantic Analysis ========== */
    printf("\n[2/4] Semantik analiz (tip kontrolu)...\n");
    
    SemanticAnalyzer *analyzer = semantic_create();
    bool semantic_ok = semantic_analyze(analyzer, ast_root);
    
    /* Show symbol table if requested */
    if (opts.show_symbols) {
        SymbolTable *symtab = semantic_get_symbol_table(analyzer);
        symbol_table_print(symtab);
    }
    
    if (!semantic_ok) {
        printf("\n");
        semantic_print_errors(analyzer);
        semantic_destroy(analyzer);
        ast_free(ast_root);
        return EXIT_FAILURE;
    }
    
    printf("      Semantik analiz basarili.\n");
    
    /* ========== Phase 3: Code Generation ========== */
    printf("\n[3/4] Kod uretimi (bytecode)...\n");
    
    SymbolTable *symtab = semantic_get_symbol_table(analyzer);
    CodeGenerator *codegen = codegen_create(symtab);
    Bytecode *bc = codegen_generate(codegen, ast_root);
    
    if (!bc) {
        fprintf(stderr, "Bytecode uretilemedi.\n");
        codegen_destroy(codegen);
        semantic_destroy(analyzer);
        ast_free(ast_root);
        return EXIT_FAILURE;
    }
    
    printf("      Bytecode uretildi: %d instruction.\n", bc->code_size);
    
    /* Show bytecode if requested */
    if (opts.show_bytecode) {
        bytecode_print(bc);
    }
    
    /* Save bytecode to file if requested */
    if (opts.output_file) {
        bytecode_save(bc, opts.output_file);
    }
    
    /* ========== Phase 4: Execution ========== */
    int exit_code = 0;
    
    if (opts.run_program) {
        printf("\n[4/4] Program calistiriliyor...\n");
        
        VM *vm = vm_create();
        vm_set_debug(vm, opts.debug_vm);
        
        printf("\n--- Program Ciktisi ---\n");
        exit_code = vm_execute(vm, bc);
        printf("--- Program Sonu ---\n");
        
        printf("\nProgram cikis kodu: %d\n", exit_code);
        
        vm_destroy(vm);
    } else {
        printf("\n[4/4] Program calistirilmadi (-r ile calistirilabilir).\n");
    }
    
    /* Cleanup */
    codegen_destroy(codegen);
    bytecode_free(bc);
    semantic_destroy(analyzer);
    symbol_table_destroy(symtab);
    ast_free(ast_root);
    
    printf("\n=== Derleme Tamamlandi ===\n");
    return exit_code;
}
